# core/video_pdf_report.py
from fpdf import FPDF
import os

class VideoReportPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 10)
        self.cell(0, 10, 'Oracle Forensic System v1.0 (Video Report)', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 10, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 8, body)
        self.ln()

def generate_video_pdf(case_data, output_path):
    pdf = VideoReportPDF()
    pdf.add_page()
    
    # Safely get case info
    case_info = case_data.get('case', {})
    
    # --- PAGE 1: COVER ---
    pdf.set_font('Arial', 'B', 24)
    pdf.ln(40)
    pdf.cell(0, 10, 'VIDEO FORENSIC REPORT', 0, 1, 'C')
    pdf.ln(10)
    
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f"Case ID: {case_info.get('case_id', 'Unknown')}", 0, 1, 'C')
    pdf.cell(0, 10, f"Generated By: {case_data.get('user', 'Unknown')}", 0, 1, 'C')
    pdf.cell(0, 10, f"Date: {case_info.get('generated_at', 'N/A')}", 0, 1, 'C')
    pdf.ln(20)
    
    # Disclaimer
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 5, case_info.get('disclaimer', 'AI-Assisted Report'))
    
    # --- PAGE 2: METADATA & ANALYSIS ---
    pdf.add_page()
    pdf.chapter_title("1. Video Metadata")
    
    scene = case_data.get('scene', {})
    video_info = case_data.get('video', {})
    
    pdf.set_font('Arial', '', 11)
    
    # Safe access to video path
    video_path = video_info.get('path', 'Unknown')
    pdf.cell(0, 8, f"Video File: {os.path.basename(video_path)}", 0, 1)
    pdf.cell(0, 8, f"FPS: {scene.get('video_fps', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Total Frames Analyzed: {scene.get('total_frames_analyzed', 0)}", 0, 1)
    
    analysis = case_data.get('analysis', {})
    severity = analysis.get('severity', {})
    pdf.cell(0, 8, f"Severity Score: {severity.get('score', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Severity Level: {severity.get('level', 'N/A')}", 0, 1)
    pdf.ln(10)

    # --- PAGE 3: TIMELINE ---
    pdf.chapter_title("2. Event Timeline")
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(30, 8, "Time (s)", 1)
    pdf.cell(30, 8, "Frame", 1)
    pdf.cell(130, 8, "Event Description", 1)
    pdf.ln()
    
    pdf.set_font('Arial', '', 10)
    timeline = case_data.get('timeline', [])
    
    # ✅ FIX: Iterate safely. If 't' is not a dict, skip it.
    valid_events = 0
    for t in timeline:
        if valid_events >= 25: break # Limit to fit page
        
        # Guard against corrupted data (strings instead of dicts)
        if not isinstance(t, dict):
            continue
            
        timestamp = t.get('timestamp_sec', 'N/A')
        frame = t.get('frame', 'N/A')
        
        pdf.cell(30, 8, f"+{timestamp}s", 1)
        pdf.cell(30, 8, str(frame), 1)
        pdf.cell(130, 8, "Activity Detected", 1) 
        pdf.ln()
        valid_events += 1
    
    if len(timeline) > 25:
        pdf.cell(0, 8, "... (More events in full digital report)", 0, 1)
    pdf.ln(10)

    # --- PAGE 4: DETECTED PLATES ---
    pdf.add_page()
    pdf.chapter_title("3. Detected License Plates")
    
    # Check both locations (root or entities)
    plates = case_data.get('license_plates', [])
    if not plates and 'entities' in case_data:
        plates = case_data['entities'].get('license_plates', [])

    if plates:
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(50, 8, "Plate Number", 1)
        pdf.cell(40, 8, "Timestamp", 1)
        pdf.cell(40, 8, "Confidence", 1)
        pdf.cell(40, 8, "Frame Index", 1)
        pdf.ln()
        
        pdf.set_font('Arial', '', 10)
        for p in plates:
            # ✅ FIX: Guard against non-dict items here too
            if not isinstance(p, dict): continue

            pdf.cell(50, 8, str(p.get('plate', 'Unknown')), 1)
            pdf.cell(40, 8, f"{p.get('timestamp_sec', 0)}s", 1)
            pdf.cell(40, 8, str(p.get('confidence', 0)), 1)
            pdf.cell(40, 8, str(p.get('frame_index', 'N/A')), 1)
            pdf.ln()
    else:
        pdf.cell(0, 8, "No license plates detected.", 0, 1)
    pdf.ln(10)

    # --- PAGE 5: NARRATIVE ---
    pdf.chapter_title("4. AI Narrative Reconstruction")
    
    narrative_data = case_data.get('narrative', {})
    if isinstance(narrative_data, dict):
        narrative = narrative_data.get('reconstruction', 'No narrative available.')
    else:
        narrative = str(narrative_data)
        
    pdf.multi_cell(0, 6, narrative)
    pdf.ln(10)

    # --- PAGE 6: CHAIN OF CUSTODY ---
    pdf.chapter_title("5. Chain of Custody")
    custody = case_data.get('chain_of_custody', {})
    
    pdf.set_font('Courier', '', 10)
    pdf.multi_cell(0, 6, f"FILE HASH: {custody.get('file_hash', 'N/A')}")
    pdf.multi_cell(0, 6, f"HANDLED BY: {custody.get('handled_by', 'N/A')}")
    pdf.multi_cell(0, 6, f"TIMESTAMP:  {custody.get('timestamp', 'N/A')}")

    pdf.output(output_path)